;(function () {var DUP_OPEN="BAIDU_DUP3",DUP_TM="BAIDU_DUP2_SETJSONADSLOT",VERSION_NUMBER="1413968038",require=window[DUP_OPEN+"_require"],define=window[DUP_OPEN+"_define"],POS_URL="http://pos.baidu.com/ecom?";
define&&define("union/common/bom1413968038",[],function(){var j={};/msie (\d+\.\d)/i.test(navigator.userAgent)&&(j.ie=document.documentMode||+RegExp.$1);/opera\/(\d+\.\d)/i.test(navigator.userAgent)&&(j.opera=+RegExp.$1);/firefox\/(\d+\.\d)/i.test(navigator.userAgent)&&(j.firefox=+RegExp.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(navigator.userAgent)&&!/chrome/i.test(navigator.userAgent)&&(j.safari=+(RegExp.$1||RegExp.$2));/chrome\/(\d+\.\d)/i.test(navigator.userAgent)&&(j.chrome=+RegExp.$1);
try{/(\d+\.\d)/.test(window.external.max_version)&&(j.maxthon=+RegExp.$1)}catch(h){}j.isWebkit=/webkit/i.test(navigator.userAgent);j.isGecko=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);j.isStrict="CSS1Compat"==document.compatMode;return{browser:j,canFixed:function(){var a=!0;if(this.browser.ie&&(7>this.browser.ie||"BackCompat"===document.compatMode))a=!1;return a},getScrollWidth:function(a){try{return a=a||window,"BackCompat"===a.document.compatMode?a.document.body.scrollWidth:
a.document.documentElement.scrollWidth}catch(i){return 0}},getScrollHeight:function(a){try{return a=a||window,"BackCompat"===a.document.compatMode?a.document.body.scrollHeight:a.document.documentElement.scrollHeight}catch(i){return 0}},getClientWidth:function(a){try{return a=a||window,"BackCompat"===a.document.compatMode?a.document.body.clientWidth:a.document.documentElement.clientWidth}catch(i){return 0}},getClientHeight:function(a){try{return a=a||window,"BackCompat"===a.document.compatMode?a.document.body.clientHeight:
a.document.documentElement.clientHeight}catch(i){return 0}},getScrollTop:function(a){a=(a||window).document;return window.pageYOffset||a.documentElement.scrollTop||a.body.scrollTop},getScrollLeft:function(a){a=(a||window).document;return window.pageXOffset||a.documentElement.scrollLeft||a.body.scrollLeft},isWindow:function(a){var i=!1;try{a&&"object"===typeof a&&a.document&&"setInterval"in a&&(i=!0)}catch(b){i=!1}return i},isInIframe:function(a){a=a||window;return a!=window.top&&a!=a.parent||!this.isWindow(a)},
isInCrossDomainIframe:function(a,i){for(var i=2===arguments.length?i:a.parent,b=0;10>b++&&this.isInIframe(a,i);){var d;try{d=!!a.parent.location.toString()}catch(c){d=!1}if(!d)return!0;a=a.parent}return 10<=b?!0:!1},sendRequestViaImage:function(a,i){var b=new Image,d="cpro_log_"+Math.floor(2147483648*Math.random()).toString(36),i=i||window;i[d]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=null;b=i[d]=null};b.src=a},getDocument:function(a){if(!a)return document;"string"===
typeof a&&(a=document.getElementById(a));return 9===a.nodeType?a:a.ownerDocument||a.document},getWindow:function(a){"string"===typeof a&&(a=document.getElementById(a));a=this.getDocument(a);return a.parentWindow||a.defaultView||null},getTopWindow:function(a){a=a||window;return this.isInIframe(a)&&!this.isInCrossDomainIframe(a,a.top)&&this.isWindow(a.top)?a.top:a}}});
define&&define("union/common/cookie1413968038",[],function(){return{getRaw:function(j,h){var a,i=RegExp("(^| )"+j+"=([^;]*)(;|$)").exec((h||window).document.cookie);i&&(a=i[2]);return a},setRaw:function(j,h,a){var a=a||{},i=a.expires;"number"==typeof a.expires&&(i=new Date,i.setTime(i.getTime()+a.expires));document.cookie=""+j+"="+h+(a.path?"; path="+a.path:"")+(i?"; expires="+i.toGMTString():"")+(a.domain?"; domain="+a.domain:"")+(a.secure?"; secure":"")},remove:function(j){var h=new Date;h.setTime(h.getTime()-
86400);this.setRaw(j,"",{path:"/",expires:h})}}});
define&&define("union/common/dom1413968038",["union/common/oo1413968038","union/common/bom1413968038"],function(j,h){return j(function(a){var i=h.browser;return{g:function(b,d){return"string"===typeof b||b instanceof String?(d||window).document.getElementById(b):b},is:function(b,d){var c=!0;if("string"===typeof d)return b.id===d;if(d.constructor===Object)return a.each(d,function(d,a){var f=(b.getAttribute?b.getAttribute(a):b[a])||b[a];if("tagName"===a){if(f.toUpperCase()!=d.toUpperCase())return c=
!1}else if(f!=d)return c=!1}),c;if(d.constructor===Array){var f=d.concat([]);f.reverse();for(var g=b;g&&f.length;g=g.parentNode)this.is(g,f[0])&&f.shift();return!f.length?!0:!1}},traverse:function(b,d){if(b&&!1!==d(b)){var a=b.childNodes;if(a)for(var f=0,g=a.length;f<g;f++)if(!1===this.traverse(a[f],d))return!1}},subOne:function(b,d){var a=this;b.constructor===Object&&(b=this.one(b));if("string"===typeof d){for(var f=document.getElementById(d),g=f;g;){if(g===b)return f;g=g.parentNode}return null}if(d.constructor===
Object){var i=null;a.traverse(b,function(b){if(a.is(b,d))return i=b,!1});return i}},one:function(b){if(b){if(b.nodeName)return b;1<arguments.length&&(b=Array.prototype.slice.call(arguments,0));if("string"===typeof b)return document.getElementById(b);if(b.constructor===Object)return this.subOne(document.documentElement,b);if(b.constructor===Array){for(var d=b.concat([]),a=document.documentElement;d.length&&a;)a=this.subOne(a,d.shift());return a}}},ready:function(b,d,c){var c=c||this.win||window,f=
c.document;this.domReadyMonitorRunTimes=0;this.readyFuncArray=this.readyFuncArray||[];this.readyFuncArray.push({func:b,delay:d||0,done:!1});var g=a.proxy(function(){var b=!1;this.domReadyMonitorRunTimes++;var d=!1;try{c.frameElement&&(d=!0)}catch(a){d=!0}if(i.ie&&9>i.ie&&!d)try{f.documentElement.doScroll("left"),b=!0}catch(g){}else if("complete"===f.readyState||this.domContentLoaded)b=!0;else if(3E5<this.domReadyMonitorRunTimes){this.domReadyMonitorId&&(c.clearInterval(this.domReadyMonitorId),this.domReadyMonitorId=
null);return}if(b)try{if(this.readyFuncArray&&this.readyFuncArray.length)for(var b=0,e=this.readyFuncArray.length;b<e;b++){var n=this.readyFuncArray[b];n&&n.func&&!n.done&&(n.delay?(n.done=!0,c.setTimeout(n.func,n.delay)):(n.done=!0,n.func()))}}catch(r){throw r;}finally{this.domReadyMonitorId&&(c.clearInterval(this.domReadyMonitorId),this.domReadyMonitorId=null)}},this),b=a.proxy(function(){this.domContentLoaded=!0;g()},this);this.domReadyMonitorId||(this.domReadyMonitorId=c.setInterval(g,50),f.addEventListener?
(f.addEventListener("DOMContentLoaded",b,!1),c.addEventListener("load",b,!1)):f.attachEvent&&c.attachEvent("onload",b,!1))},canFixed:function(){var b=!0;if(i.ie&&(7>i.ie||"BackCompat"===document.compatMode))b=!1;return b},bind:function(b,d,a){"string"===typeof b&&(b=this.one(b));d=d.replace(/^on/i,"").toLowerCase();b.addEventListener?b.addEventListener(d,a,!1):b.attachEvent&&b.attachEvent("on"+d,a);return b},unbind:function(b,d,a){b=this.one(b);if(!b)return null;d=d.replace(/^on/i,"").toLowerCase();
b.removeEventListener?b.removeEventListener(d,a,!1):b.detachEvent&&b.detachEvent("on"+d,a);return b},getStyle:function(b,d){var a;"string"===typeof b&&(b=this.one(b));var f=h.getDocument(b),g="",g=-1<d.indexOf("-")?d.replace(/[-_][^-_]{1}/g,function(b){return b.charAt(1).toUpperCase()}):d.replace(/[A-Z]{1}/g,function(b){return"-"+b.charAt(0).toLowerCase()});f&&f.defaultView&&f.defaultView.getComputedStyle?((f=f.defaultView.getComputedStyle(b,null))&&(a=f.getPropertyValue(d)),"boolean"!==typeof a&&
!a&&(a=f.getPropertyValue(g))):b.currentStyle&&((f=b.currentStyle)&&(a=f[d]),"boolean"!==typeof a&&!a&&(a=f[g]));return a},getPosition:function(b,d){d=d||window;"string"===typeof b&&(b=this.one(b));if(b){for(var a=this.getPositionCore(b),f,g=0;d!=d.parent&&10>g;)g++,f=this.getPositionCore(d.frameElement),a.left+=f.left,a.top+=f.top,d=d.parent;return a}},getPositionCore:function(b){"string"===typeof b&&(b=this.one(b));var a=h.getDocument(b),c=h.browser;0<c.isGecko&&a.getBoxObjectFor&&this.getStyle(b,
"position");var f={left:0,top:0},g;if(b==(c.ie&&!c.isStrict?a.body:a.documentElement)||!b)return f;if(b.getBoundingClientRect)b=b.getBoundingClientRect(),f.left=Math.floor(b.left)+Math.max(a.documentElement.scrollLeft,a.body.scrollLeft),f.top=Math.floor(b.top)+Math.max(a.documentElement.scrollTop,a.body.scrollTop),f.left-=a.documentElement.clientLeft,f.top-=a.documentElement.clientTop,b=a.body,a=parseInt(this.getStyle(b,"borderLeftWidth"),10),b=parseInt(this.getStyle(b,"borderTopWidth"),10),c.ie&&
!c.isStrict&&(f.left-=isNaN(a)?2:a,f.top-=isNaN(b)?2:b);else{g=b;do{f.left+=g.offsetLeft;f.top+=g.offsetTop;if(0<c.isWebkit&&"fixed"==this.getStyle(g,"position")){f.left+=a.body.scrollLeft;f.top+=a.body.scrollTop;break}g=g.offsetParent}while(g&&g!=b);if(0<c.opera||0<c.isWebkit&&"absolute"==this.getStyle(b,"position"))f.top-=a.body.offsetTop;for(g=b.offsetParent;g&&g!=a.body;){f.left-=g.scrollLeft;if(!c.opera||"TR"!=g.tagName)f.top-=g.scrollTop;g=g.offsetParent}}return f},getOuterWidth:function(b,
a){var b=this.one(b),c=b.offsetWidth;if(a)var f=this.getStyle(b,"marginLeft").toString().toLowerCase().replace("px","").replace("auto","0"),g=this.getStyle(b,"marginRight").toString().toLowerCase().replace("px","").replace("auto","0"),c=c+(parseInt(f||0,10)+parseInt(g||0,10));return c},getOuterHeight:function(b,a){var b=this.one(b),c=b.offsetHeight;if(a)var f=this.getStyle(b,"marginTop").toString().toLowerCase().replace("px","").replace("auto","0"),g=this.getStyle(b,"marginBottom").toString().toLowerCase().replace("px",
"").replace("auto","0"),c=c+(parseInt(f||0,10)+parseInt(g||0,10));return c},getTopIframe:function(b){var b=this.one(b),a=this.getWindow(b),c=0;if(this.isInIframe(window)&&!h.isInCrossDomainIframe(window)){for(;a.parent!=window.top&&10>c;)c++,a=a.parent;10>c&&(b=a.frameElement||b)}return b},getOpacityInWin:function(b){var a=this.one(b),b=this.getWindow(a),c=100,f;try{for(;a&&a.tagName;){f=100;if(this.browser.ie){if(5<this.browser.ie)try{f=a.filters.alpha.opacity||100}catch(g){}c=c>f?f:c}else{try{f=
100*(b.getComputedStyle(a,null).opacity||1)}catch(i){}c*=f/100}a=a.parentNode}}catch(j){}return c||100},getOpacity:function(b){for(var a=this.one(b),b=this.getWindow(a),a=this.getOpacityInWin(a),c=100,f=0;this.isInIframe(b);){f++;if(h.isInCrossDomainIframe(b,b.parent))break;else c=100,b.frameElement&&(c=this.getOpacityInWin(b.frameElement)),a*=c/100;b=b.parent}return a}}})});
define&&define("union/common/logic1413968038",[],function(){return{escapeToEncode:function(j){(j=j||"")&&(j=j.replace(/%u[\d|\w]{4}/g,function(j){return encodeURIComponent(unescape(j))}));return j},template:function(j,h){return j.replace(/{(.*?)}/g,function(a,i){return h[i]||""})},jsonToObj:function(j){return(new Function("return "+j))()},getUrlQueryValue:function(j,h){if(j&&h){var a=j.match(RegExp("(^|&|\\?|#)"+h+"=([^&]*)(&|$)",""));if(a)return a[2]}return null},parseUrlQuery:function(j,h){var j=
j||"",h=h||"?",a=arguments.callee;a.hasOwnProperty[h]||(a[h]={});a=a[h];if(a.hasOwnProperty(j))return a[j];var i={},b=j.indexOf(h),d=j.substring(b+1).split("&");if(-1!==b)for(var b=0,c=d.length;b<c;b++){var f=d[b].split("="),g=decodeURIComponent(f[0]),f=decodeURIComponent(f[1]);i.hasOwnProperty(g)?(i[g].constructor!==Array&&(i[g]=[i[g]]),i[g].push(f)):i[g]=f}return a[j]=i}}});
define&&define("union/common/oo1413968038",[],function(){function j(b,a){if(b.constructor===Array)for(var c=0,f=b.length;c<f;c++){if(!1===a.call(b,b[c],c,b))return!1}else{var c=!{toString:1}.propertyIsEnumerable("toString"),g="toString,toLocaleString,valueOf,constructor,propertyIsEnumerable,hasOwnProperty,isPrototypeOf".split(",");for(f in b)if(b.hasOwnProperty(f)&&!1===a.call(b,b[f],f,b))return!1;if(c){c=0;for(f=g.length;c<f;c++){var i=g[c];if(b.hasOwnProperty(i)&&!1===a.call(b,i,c,b))return!1}}}return!0}
function h(b,a,c){j(a,function(a,d){if(!b.hasOwnProperty(d)||c)b[d]=a})}function a(b){function a(){}if(Object.create)return Object.create(b);a.prototype=b;return new a}var i=function(b){var a=i.create(i);return b.call(a,a,a.X)};i.X={};i.create=a;i.each=j;i.$class=function(b,a){var c=b.hasOwnProperty("constructor")?b.constructor:function(){};c.prototype=b;c.prototype.constructor=c;a=a||{};a.statics&&h(c,a.statics);return c};i.extend=function(b,d,c){var f;f=d.hasOwnProperty("constructor")?d.constructor:
function(){b.constructor.apply(this,arguments)};f.prototype=a(b.prototype);h(f.prototype,d,!0);f.prototype.constructor=f;f.prototype.$super=b.prototype;f.prototype.$Super=b;h(f,b);c=c||{};c.statics&&h(f,c.statics,!0);return f};i.namespace=function(b){var b=b.split("."),a=this.X;j(b,function(b){a.hasOwnProperty(b)||(a[b]={});a=a[b]});return a};i.proxy=function(b,a,c){return function(){c=c||[];for(var f=0,g=arguments.length;f<g;f++)c.push(arguments[f]);return b.apply(a||{},c)}};return i});
define&&define("union/business/businessLogic1413968038",["union/preview1413968038"],function(j){var h={inlay:8,"float":2,patch:2,linkunit:20,popup:1},a={inlay:0,"float":0,patch:0,linkunit:0,popup:0},i={1001:"inlay-fixed",1002:"inlay-float",2001:"float-left-middle",2002:"float-right-middle",2003:"float-left-bottom",2004:"float-right-bottom",2005:"float-top",2006:"float-bottom",2007:"float-linkunit-left",3001:"patch-webpage",3002:"patch-flash",4001:"captcha-webpage"};return{processSlotData:function(a){var d=
a._html||{},c="",f=d.conW||0,g=d.conH||0,i=POS_URL,h=a.id.split("_")[0],f=parseInt(f,10)||parseInt(a._w,10)||parseInt(a.sw,10)||parseInt(d.rsi0,10),g=parseInt(g,10)||parseInt(a._h,10)||parseInt(a.sh,10)||parseInt(d.rsi1,10),k=a.displayType,m=d.tn||"",e=m.toLowerCase(),n=d.ch||0,a=a.qn||"",r=d.n||"",l=d.dai||0;d.dtm=DUP_TM;d.dc="2";d.di=h;var c=[],o;for(o in d)o&&d.hasOwnProperty(o)&&c.push(""+o+"="+encodeURIComponent(d[o].toString()));c=c.join("&");if((o=j.getPreviewUrlData(d,k))&&void 0!==o.serviceUrl&&
void 0!==o.paramString)i=o.serviceUrl,c=o.paramString;return{slotId:h,slotWidth:f,slotHeight:g,displayType:k,styleType:e,iframeId:"cproIframe_"+h,unionAccount:r,adIndex:l,channel:n,pvId:a,stuffType:"unknown",serviceUrl:i,paramString:c,delayIn:d.delayIn,delayOut:d.delayOut,sessionSync:!1!==d.sessionSync&&"false"!==d.sessionSync,closeFor:d.closeFor,xuantingType:d.xuanting,tn:m}},processAdsCountOption:function(a){var d={};d.deviceType=(a.deviceType||"pc").toLowerCase();d.displayType=(a.displayType||
"inlay-fixed").toLowerCase();d.styleType=(a.styleType||"template_inlay_all_normal").toLowerCase();d.stuffType=(a.stuffType||"text").toLowerCase();if(-1<d.styleType.indexOf("tlink")||-1<d.styleType.indexOf("linkunit"))d.displayType="linkunit-fixed";0<=d.styleType.indexOf("float_xuanfuwin")&&(d.displayType="popup-float");a=d.displayType.split("-");d.displayMainType=a[0]||"inlay";d.displaySubType=a[1]||"fixed";return d},checkAdsCount:function(b){b=this.processAdsCountOption(b);b=b.displayMainType;return a[b]<
h[b]},getAdsCount:function(b){b=this.processAdsCountOption(b);return a[b.displayMainType]},setAdsCount:function(b){b=this.processAdsCountOption(b);a[b.displayMainType]+=1;return!0},getWrapper:function(a,d){var c=document.getElementById("cpro_"+a);c||(c=document.getElementById(d));return c},getDisplayTypeByValue:function(a){return i[a]},checkFloatLu:function(a){var d={"test.com":!0,"people.com.cn":!0,"chinanews.com":!0,"cri.cn":!0,"chinadaily.com":!0,"cnki.com.cn":!0,"cnki.net":!0,"ku6.com":!0,"tgbus.com":!0,
"5068.com":!0,"yzz.cn":!0,"aipai.com":!0,"stockstar.com":!0},a=a||window,c="",f=a.document.domain.split("."),g=f.length;g&&2<g?c="cn"===f[g-1]&&"com"===f[g-2]?f[g-3]+"."+f[g-2]+"."+f[g-1]:f[g-2]+"."+f[g-1]:g&&(c=a.document.domain);return c&&d[c]?!1:!0},setupViewWatch:function(a){var d=a.slotId;require(["viewWatch"],function(c){c.register({id:d,wrapperId:a.iframeId,logType:"block",extra:"ch="+a.channel+"&jk="+a.pvId+"&n="+a.unionAccount})},!0)}}});
define&&define("union/preview1413968038",["union/common/bom1413968038","union/common/logic1413968038","union/common/cookie1413968038"],function(j,h,a){function i(a){a=decodeURIComponent(a).replace(/\\x1e/g,"&").replace(/\\x1d/g,"=").replace(/\\x1c/g,"?").replace(/\\x5c/g,"\\");return h.jsonToObj(a)}function b(b,c){var f;f=c?c.substring(c.indexOf("?")):j.isInCrossDomainIframe(window)?window.location.search.slice(1):window.top.location.search.slice(1);var g=document.referrer,i=0<=b.indexOf("inlay")||
"ui"===b?"bd_cpro_prev":"bd_cpro_fprev",p="",k;try{k=document.cookie}catch(m){}-1!==f.indexOf(i)&&(p=h.getUrlQueryValue(f,i));!p&&k&&-1!==k.indexOf(i)&&(p=a.getRaw(i));!p&&-1!==g.indexOf(i)&&(p=h.getUrlQueryValue(g,i));return p}return{getPreviewUrlData:function(a,c){var f=window.location.href,g=parseInt(a.rsi0,10),j=parseInt(a.rsi1,10),h=parseInt(a.at,10),k=!1,m=b(c,f);if(m)if(m=i(m),void 0===h&&(h=1),1!==parseInt(m.type,10)&&2===(h&2))k=parseInt(m.imgWidth,10)===parseInt(g,10)&&parseInt(m.imgHeight,
10)===parseInt(j,10);else if(1===parseInt(m.type,10)&&(1===(h&1)||64===(h&64)||32===(h&32)))k=!0;return k?(g=0<=c.indexOf("inlay")||"ui"===c?"bd_cpro_prev":"bd_cpro_fprev",f=b(c,f),j=a.tn,h=i(f),k=null,0<=c.indexOf("inlay")?(h=parseInt(h.type,10),k={serviceUrl:"http://cpro.baidu.com/cpro/ui/preview/templates/"+(1===h?j+".html":2===h?"image.html":4===h?"flash.html":"blank_tips.html")+"?",paramString:(""+g+"=#"+f+"&ut="+ +new Date).replace(/\.(?!swf)/g,"%252e")}):"float"===c&&(h=parseInt(h.type,10),
h="http://cpro.baidu.com/cpro/ui/preview/templates/"+(2===h?"float_image.html":4===h?"float_flash.html":"blank_tips.html")+"?",g="tn="+j+("&"+g+"="+f).replace(/\./g,"%252e")+"&ut="+ +new Date,k={serviceUrl:h,paramString:g}),k):null}}});
define&&define("union/slide",["union/common/dom1413968038","union/business/businessLogic1413968038","union/common/bom1413968038"],function(j,h,a){function i(){return a.browser.ie&&7>a.browser.ie?!0:!1}function b(a){var b=new Image,f="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[f]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=null;b=window[f]=null};b.src=a}function d(){var e=this;this.isSlideEnable=function(){return e.slideInfo.enable};this.setUrl=
function(){!1==e.iframeUrlDone&&(e.dialog.src=this.getUrl(),e.iframeUrlDone=!0)};this.resetBottomLoc=function(){"left"==e.slidePos||"right"==e.slidePos?e.outerDiv.style.top=a.getScrollTop()+a.getClientHeight()-e.verticalPos-e.outer_height+"px":"bottom"==e.slidePos?e.outerDiv.style.top=a.getScrollTop()+a.getClientHeight()-e.verticalPos-e.slideDivHeight-e.slideInfo.total-e.slideInfo.move+"px":"top"==e.slidePos&&(e.outerDiv.style.top=a.getScrollTop()-e.verticalPos-e.outer_height+e.slideDivHeight+e.slideInfo.total+
e.slideInfo.move+"px")};this.parseUrl=function(a){var b={},f=a.indexOf("?");if(0>f)return b;for(var e=a.substr(f+1).split("&"),d=0;d<e.length;d++){var c=e[d].split("=");2==c.length&&(b[c[0]]=c[1])}return{urlhead:a.substr(0,f),params:b}};this.serializeUrl=function(a,b){var f=[],e;for(e in b)f.push(e+"="+b[e]);return a+"?"+f.join("&")};this.init=function(e){this.slide_cpro_id=e.cpro_id;if(!(void 0==e.curl||""==e.curl)){this.slideUrl=e.curl;var d=this.parseUrl(this.slideUrl);if(!(void 0==d.params.tn||
0>d.params.tn.indexOf("baiduTlinkInlay")&&0>d.params.tn.indexOf("baiduCustSTagLinkUnit"))){this.slideWidth=parseInt(""==d.params.rsi0||void 0==d.params.rsi0?"0":d.params.rsi0);this.slideHeight=parseInt(""==d.params.rsi1||void 0==d.params.rsi1?"0":d.params.rsi1);this.slidePos=void 0==e.cpro_slideLU_abs_pos?e.pos:e.cpro_slideLU_abs_pos;"left"!=this.slidePos&&"right"!=this.slidePos&&"bottom"!=this.slidePos&&"top"!=this.slidePos&&(this.slidePos="left");void 0==e.cpro_slideLU_rel_pos?(this.slideBottomPos=
e.bpos,this.verticalPos=parseInt(""==e.ver||void 0==e.ver?"0":e.ver)):"left"==this.slidePos||"right"==this.slidePos?(this.slideBottomPos="middle",this.verticalPos=parseInt(""==e.cpro_slideLU_rel_pos?"0":e.cpro_slideLU_rel_pos)):(this.slideBottomPos=e.cpro_slideLU_rel_pos,this.verticalPos=0);"left"!=this.slideBottomPos&&"right"!=this.slideBottomPos&&"middle"!=this.slideBottomPos&&(this.slideBottomPos="middle");if("bottom"==this.slidePos||"top"==this.slidePos)this.verticalPos=0;this.slidePercent=void 0==
e.cpro_slideLU_out_per?parseFloat(""==e.per||void 0==e.per?"0":e.per):parseFloat(""==e.cpro_slideLU_out_per?"0":e.cpro_slideLU_out_per);this.slideEndPercent=void 0==e.cpro_slideLU_in_per?parseFloat(""==e.per2||void 0==e.per2?"1":e.per2):parseFloat(""==e.cpro_slideLU_in_per?"0":e.cpro_slideLU_in_per);0.1>this.slideEndPercent-this.slidePercent&&(this.slideEndPercent=this.slidePercent+0.1);if(this.slidePercent>this.slideEndPercent||1<this.slideEndPercent)this.slideEndPercent=1;if(("bottom"==this.slidePos||
"top"==this.slidePos)&&"rsi1"in d.params&&75<parseInt(d.params.rsi1))"hn"in d.params&&(e=d.params.hn,d.params.hn=Math.floor(75*parseInt(d.params.hn)/parseInt(d.params.rsi1)),"adn"in d.params&&(d.params.adn=Math.floor(parseInt(d.params.adn)*parseInt(d.params.hn)/parseInt(e)),d.params.adn=Math.max(parseInt(d.params.adn),parseInt(d.params.hn)*parseInt(d.params.wn)))),this.slideHeight=d.params.rsi1=75;if(("left"==this.slidePos||"right"==this.slidePos)&&"rsi0"in d.params&&450<parseInt(d.params.rsi0))"wn"in
d.params&&(e=d.params.wn,d.params.wn=Math.floor(450*parseInt(d.params.wn)/parseInt(d.params.rsi0)),"adn"in d.params&&(d.params.adn=Math.floor(parseInt(d.params.adn)*parseInt(d.params.wn)/parseInt(e)),d.params.adn=Math.max(parseInt(d.params.adn),parseInt(d.params.hn)*parseInt(d.params.wn)))),this.slideWidth=d.params.rsi0=450;"stid"in d.params?"0"==d.params.stid?d.params.stid="14":"5"==d.params.stid&&(d.params.stid="15"):d.params.stid="14";this.slideUrl=this.serializeUrl(d.urlhead,d.params);var d={tu:this.slide_cpro_id,
rsi0:this.slideWidth,rsi1:this.slideHeight,pos:this.slidePos,bpos:this.slideBottomPos,per:this.slidePercent,per2:this.slideEndPercent,ver:this.verticalPos,random:+new Date},l,e="module=slide",h;for(h in d)e+="&"+h+"="+d[h];b("http://eclick.baidu.com/preshow.jpg?"+e);this.slideIsBarTitle=!0;this.iframeUrlDone=!1;this.scaleFactor=4.5;this.slideDivBtnBgSize=16;this.specSize=2;if("left"==this.slidePos||"right"==this.slidePos)102<=this.slideHeight?(this.slideDivWidth=30,this.slideBarTitleFontSize=16):
89<=this.slideHeight?(this.slideDivWidth=26,this.slideBarTitleFontSize=14):76<=this.slideHeight?(this.specSize=0,this.slideDivWidth=22,this.slideBarTitleFontSize=12):(this.specSize=0,this.slideDivWidth=22,this.slideBarTitleFontSize=12,this.slideIsBarTitle=!1),this.slideDivHeight=this.slideIsBarTitle?this.slideBarTitleFontSize*this.scaleFactor+this.slideDivWidth:this.slideDivWidth;else if("bottom"==this.slidePos||"top"==this.slidePos)this.slideDivHeight=30,this.slideBarTitleFontSize=16,this.slideDivWidth=
this.slideIsBarTitle?this.slideBarTitleFontSize*this.scaleFactor+this.slideDivHeight:this.slideDivHeight;this.slideDivBgColor="#518CFF";this.iframeDivBorderWidth=1;this.iframeDivBorderColor="#518CFF";this.iframeBorderShadowSize=30;this.iframeBorderShadowSize>this.slideDivHeight&&(this.iframeBorderShadowSize=this.slideDivHeight);this.iframeBorderSpreadSize=5;if("top"==this.slidePos||"bottom"==this.slidePos)this.iframeDivBorderColor="#a2a2a2";if("left"==this.slidePos||"right"==this.slidePos)this.outer_width=
this.slideWidth+2*this.iframeDivBorderWidth+this.slideDivWidth,this.outer_height=this.slideHeight+2*this.iframeDivBorderWidth;else if("bottom"==this.slidePos||"top"==this.slidePos)this.outer_width=this.slideWidth+2*this.iframeDivBorderWidth+2*this.iframeBorderShadowSize,this.outer_height=this.slideHeight+2*this.iframeDivBorderWidth+this.slideDivHeight;this.slideInfo={};if("left"==this.slidePos||"right"==this.slidePos)this.slideInfo.total=this.slideWidth+2*this.iframeDivBorderWidth;else if("bottom"==
this.slidePos||"top"==this.slidePos)this.slideInfo.total=this.slideHeight+2*this.iframeDivBorderWidth;this.slideInfo.move=-this.slideInfo.total;this.slideInfo.interval=this.slideInfo.total/6;this.slideInfo.speed=50;this.slideInfo.enable=!0;this.outerDiv=document.createElement("div");h="width:"+this.outer_width+"px;height:"+this.outer_height+"px;overflow:hidden;z-index:2147483649;";if("left"==this.slidePos||"right"==this.slidePos)this.outerDiv.style.cssText=i()?"position:absolute;top:"+(a.getScrollTop()+
a.getClientHeight()-this.verticalPos-this.outer_height)+"px;"+this.slidePos+":-"+(this.outer_width-this.slideDivWidth)+"px;"+h:"position:fixed;bottom:"+this.verticalPos+"px; "+this.slidePos+":-"+(this.outer_width-this.slideDivWidth)+"px;"+h;else if("bottom"==this.slidePos||"top"==this.slidePos)i()?"middle"==this.slideBottomPos?("bottom"==this.slidePos?l=a.getScrollTop()+a.getClientHeight()-this.verticalPos-this.slideDivHeight-this.slideInfo.total-this.slideInfo.move:"top"==this.slidePos&&(l=a.getScrollTop()-
this.verticalPos-this.outer_height+this.slideDivHeight+this.slideInfo.total+this.slideInfo.move),this.outerDiv.style.cssText="position:absolute;top:"+l+"px;left:"+(a.getClientWidth()-this.outer_width)/2+"px;"+h):"left"==this.slideBottomPos?("bottom"==this.slidePos?l=a.getScrollTop()+a.getClientHeight()-this.verticalPos-this.slideDivHeight-this.slideInfo.total-this.slideInfo.move:"top"==this.slidePos&&(l=a.getScrollTop()-this.verticalPos-this.outer_height+this.slideDivHeight+this.slideInfo.total+this.slideInfo.move),
this.outerDiv.style.cssText="position:absolute;top:"+l+"px;left:-"+this.iframeBorderShadowSize+"px;"+h):"right"==this.slideBottomPos&&("bottom"==this.slidePos?l=a.getScrollTop()+a.getClientHeight()-this.verticalPos-this.slideDivHeight-this.slideInfo.total-this.slideInfo.move:"top"==this.slidePos&&(l=a.getScrollTop()-this.verticalPos-this.outer_height+this.slideDivHeight+this.slideInfo.total+this.slideInfo.move),this.outerDiv.style.cssText="position:absolute;top:"+l+"px;right:-"+this.iframeBorderShadowSize+
"px;"+h):"middle"==this.slideBottomPos?this.outerDiv.style.cssText="position:fixed;left:"+(a.getClientWidth()-this.outer_width)/2+"px;"+this.slidePos+":-"+(this.outer_height-this.slideDivHeight)+"px;"+h:"left"==this.slideBottomPos?this.outerDiv.style.cssText="position:fixed;left:-"+this.iframeBorderShadowSize+"px; "+this.slidePos+":-"+(this.outer_height-this.slideDivHeight)+"px;"+h:"right"==this.slideBottomPos&&(this.outerDiv.style.cssText="position:fixed;right:-"+this.iframeBorderShadowSize+"px;"+
this.slidePos+":-"+(this.outer_height-this.slideDivHeight)+"px;"+h);this.outerDiv.setAttribute("id","slideout"+this.slide_cpro_id);this.iframeDiv=document.createElement("div");l="#7c7c7c 0px 0px "+this.iframeBorderShadowSize+"px "+this.iframeBorderSpreadSize+"px";h="width:"+this.slideWidth+"px;height:"+this.slideHeight+"px;border:"+this.iframeDivBorderWidth+"px solid "+this.iframeDivBorderColor+";background-color:#fff;";"left"==this.slidePos?this.iframeDiv.style.cssText="left:0px;top:0px;position:absolute;"+
h:"right"==this.slidePos?this.iframeDiv.style.cssText="position:absolute;left:"+this.slideDivWidth+"px;top:0px;"+h:"bottom"==this.slidePos?this.iframeDiv.style.cssText="left:"+this.iframeBorderShadowSize+"px;top:"+this.slideDivHeight+"px;position:absolute;"+h+"box-shadow:"+l+";-webkit-box-shadow:"+l+";":"top"==this.slidePos&&(this.iframeDiv.style.cssText="left:"+this.iframeBorderShadowSize+"px;top:0px;position:absolute;"+h+"box-shadow:"+l+";-webkit-box-shadow:"+l+";");this.dialog=document.createElement("iframe");
this.dialog.style.cssText="width:"+this.slideWidth+"px;height:"+this.slideHeight+"px;";this.dialog.setAttribute("scrolling","no");this.dialog.setAttribute("frameBorder","0");this.dialog.setAttribute("allowTransparency","true");this.dialog.setAttribute("align","center,center");this.iframeDiv.appendChild(this.dialog);this.barDivA=document.createElement("a");this.barDivA.style.cssText="cursor:pointer;text-decoration:none;";this.barDivA.setAttribute("href","javascript:void(0);");this.barDivA.onclick=
this.slidebarBtnClick;l="height:"+this.slideDivHeight+"px;width:"+this.slideDivWidth+"px;background-color:"+this.slideDivBgColor+";";h="height:"+this.slideDivBtnBgSize+"px;width:"+this.slideDivBtnBgSize+"px;";d="color:#fff;font-size:"+(this.slideBarTitleFontSize-1)+"px;font-family:microsoft yahei;font-weight:bold;";"left"==this.slidePos?(this.barDiv=document.createElement("div"),this.barDiv.style.cssText="position:absolute;"+l+"left:"+(this.outer_width-this.slideDivWidth)+"px;top:0px;-moz-border-radius:0px 5px 5px 0px;-webkit-border-radius:0px 5px 5px 0px;border-radius:0px 5px 5px 0px;",
this.barBtnDiv=document.createElement("div"),this.barBtnDiv.style.cssText="position:absolute;left:"+(this.slideDivWidth-this.slideDivBtnBgSize)/2+"px;top:"+(this.slideDivWidth-this.slideDivBtnBgSize)/2+"px;"+h+"background:url("+f+") no-repeat center center;",this.slideIsBarTitle&&(this.barTitle=document.createElement("div"),this.barTitle.style.cssText="position:absolute;height:"+(this.slideDivHeight-this.slideDivWidth)+"px;width:"+this.slideDivWidth+"px;top:"+(this.slideDivWidth-this.specSize)+"px;text-align:center;"+
d+"line-height:"+this.slideBarTitleFontSize+"px",this.barTitle.innerHTML="\u4e3a<br>\u60a8<br>\u63a8<br>\u8350")):"right"==this.slidePos?(this.barDiv=document.createElement("div"),this.barDiv.style.cssText="position:absolute;"+l+"left:0px;top:0px;-moz-border-radius:5px 0px 0px 5px;-webkit-border-radius:5px 0px 0px 5px;border-radius:5px 0px 0px 5px;",this.barBtnDiv=document.createElement("div"),this.barBtnDiv.style.cssText="position:absolute;left:"+(this.slideDivWidth-this.slideDivBtnBgSize)/2+"px;top:"+
(this.slideDivWidth-this.slideDivBtnBgSize)/2+"px;"+h+"background:url("+c+") no-repeat center center;",this.slideIsBarTitle&&(this.barTitle=document.createElement("div"),this.barTitle.style.cssText="position:absolute;height:"+(this.slideDivHeight-this.slideDivWidth)+"px;width:"+this.slideDivWidth+"px;top:"+(this.slideDivWidth-this.specSize)+"px;text-align:center;"+d+"line-height:"+this.slideBarTitleFontSize+"px",this.barTitle.innerHTML="\u4e3a<br>\u60a8<br>\u63a8<br>\u8350")):"bottom"==this.slidePos?
(this.barDiv=document.createElement("div"),this.barDiv.style.cssText="position:absolute;"+l+"right:"+this.iframeBorderShadowSize+"px;top:0px;-moz-border-radius:5px 5px 0px 0px;-webkit-border-radius:5px 5px 0px 0px;border-radius:5px 5px 0px 0px;",this.barBtnDiv=document.createElement("div"),this.barBtnDiv.style.cssText="position:absolute;right:"+(this.slideDivHeight-this.slideDivBtnBgSize)/2+"px;top:"+(this.slideDivHeight-this.slideDivBtnBgSize)/2+"px;"+h+"background:url("+g+") no-repeat center center;",
this.slideIsBarTitle&&(this.barTitle=document.createElement("div"),this.barTitle.style.cssText="position:absolute;height:"+this.slideDivHeight+"px;width:"+(this.slideDivWidth-this.slideDivHeight)+"px;right:"+(this.slideDivHeight-this.specSize)+"px;text-align:right;"+d+"line-height:"+this.slideDivHeight+"px",this.barTitle.innerHTML="\u4e3a\u60a8\u63a8\u8350")):"top"==this.slidePos&&(this.barDiv=document.createElement("div"),this.barDiv.style.cssText="position:absolute;"+l+"right:"+this.iframeBorderShadowSize+
"px;top:"+(this.outer_height-this.slideDivHeight)+"px;-moz-border-radius:0px 0px 5px 5px;-webkit-border-radius:0px 0px 5px 5px;border-radius:0px 0px 5px 5px;",this.barBtnDiv=document.createElement("div"),this.barBtnDiv.style.cssText="position:absolute;right:"+(this.slideDivHeight-this.slideDivBtnBgSize)/2+"px;top:"+(this.slideDivHeight-this.slideDivBtnBgSize)/2+"px;"+h+"background:url("+q+") no-repeat center center;",this.slideIsBarTitle&&(this.barTitle=document.createElement("div"),this.barTitle.style.cssText=
"position:absolute;height:"+this.slideDivHeight+"px;width:"+(this.slideDivWidth-this.slideDivHeight)+"px;right:"+(this.slideDivHeight-this.specSize)+"px;text-align:right;"+d+"line-height:"+this.slideDivHeight+"px;",this.barTitle.innerHTML="\u4e3a\u60a8\u63a8\u8350"));this.barDiv.appendChild(this.barBtnDiv);this.slideIsBarTitle&&this.barDiv.appendChild(this.barTitle);this.barDivA.appendChild(this.barDiv);this.outerDiv.appendChild(this.iframeDiv);this.outerDiv.appendChild(this.barDivA);document.body.appendChild(this.outerDiv)}}};
this.getUrl=function(){return e.slideUrl};this.slidebarBtnClick=function(){e.slideInfo.enable=!1;0==e.slideInfo.move?e.slidein():(e.setUrl(),e.slideout());return!1};this.slideout=function(){e.slideTimer&&clearTimeout(e.slideTimer);e._slideout()};this._slideout=function(){0>e.slideInfo.move?(e.slideInfo.move+=e.slideInfo.interval,0<e.slideInfo.move&&(e.slideInfo.move=0),"right"==e.slidePos?e.outerDiv.style.right=e.slideInfo.move+"px":"left"==e.slidePos?e.outerDiv.style.left=e.slideInfo.move+"px":"bottom"==
e.slidePos?i()?e.outerDiv.style.top=a.getScrollTop()+a.getClientHeight()-e.verticalPos-e.slideDivHeight-e.slideInfo.total-e.slideInfo.move+"px":e.outerDiv.style.bottom=e.slideInfo.move+"px":"top"==e.slidePos&&(e.outerDiv.style.top=i()?a.getScrollTop()-e.verticalPos-e.outer_height+e.slideDivHeight+e.slideInfo.total+e.slideInfo.move+"px":e.slideInfo.move+"px"),e.slideTimer=setTimeout(e._slideout,e.slideInfo.speed)):"right"==e.slidePos?e.barBtnDiv.style.background="url("+f+") no-repeat center center":
"left"==e.slidePos?e.barBtnDiv.style.background="url("+c+") no-repeat center center":"bottom"==e.slidePos?e.barBtnDiv.style.background="url("+q+") no-repeat center center":"top"==e.slidePos&&(e.barBtnDiv.style.background="url("+g+") no-repeat center center")};this.slidein=function(){e.slideTimer&&clearTimeout(e.slideTimer);e._slidein()};this._slidein=function(){e.slideInfo.move>-e.slideInfo.total?(e.slideInfo.move-=e.slideInfo.interval,e.slideInfo.move<-e.slideInfo.total&&(e.slideInfo.move=-e.slideInfo.total),
"right"==e.slidePos?e.outerDiv.style.right=e.slideInfo.move+"px":"left"==e.slidePos?e.outerDiv.style.left=e.slideInfo.move+"px":"bottom"==e.slidePos?i()?e.outerDiv.style.top=a.getScrollTop()+a.getClientHeight()-e.verticalPos-e.slideDivHeight-e.slideInfo.total-e.slideInfo.move+"px":e.outerDiv.style.bottom=e.slideInfo.move+"px":"top"==e.slidePos&&(e.outerDiv.style.top=i()?a.getScrollTop()-e.verticalPos-e.outer_height+e.slideDivHeight+e.slideInfo.total+e.slideInfo.move+"px":e.slideInfo.move+"px"),e.slideTimer=
setTimeout(e._slidein,e.slideInfo.speed)):"right"==e.slidePos?e.barBtnDiv.style.background="url("+c+") no-repeat center center":"left"==e.slidePos?e.barBtnDiv.style.background="url("+f+") no-repeat center center":"bottom"==e.slidePos?e.barBtnDiv.style.background="url("+g+") no-repeat center center":"top"==e.slidePos&&(e.barBtnDiv.style.background="url("+q+") no-repeat center center")}}var c="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/left.png",f="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/right.png",
g="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/up.png",q="http://cpro.baidustatic.com/cpro/ui/noexpire/img/slide/down.png",p=function(){var b=a.getScrollTop()+a.getClientHeight()-a.getScrollHeight();if("BackCompat"==document.compatMode)var b=document.body.clientHeight,d=document.body.scrollHeight,f=document.body.scrollTop;else b=document.documentElement.clientHeight,d=document.documentElement.scrollHeight,f=0==document.documentElement.scrollTop?document.body.scrollTop:document.documentElement.scrollTop;
var b=(f+b)/d,c;for(c in k)i()&&k[c].resetBottomLoc(),k[c].isSlideEnable()&&(b>k[c].slidePercent&&b<=k[c].slideEndPercent?(k[c].setUrl(),k[c].slideout()):k[c].slidein())},k=k||{},m=!1;return{render:function(a,b){var f=j.g(b);f&&f.parentNode&&f.parentNode.removeChild(f);a.displayType="float-slide";var f=a.id,c=a._html;c.cpro_id=f;var g=h.processSlotData(a);void 0!=c.cpro_slideLU_abs_pos||void 0!=c.slideLU_abs_pos?(c.pos=c.cpro_slideLU_abs_pos||c.slideLU_abs_pos,c.cpro_slideLU_abs_pos=c.cpro_slideLU_abs_pos||
c.slideLU_abs_pos):void 0!=c.pos?c.cpro_slideLU_abs_pos=c.pos:(c.cpro_slideLU_abs_pos="left",c.pos="left");void 0!=c.cpro_slideLU_rel_pos||void 0!=c.slideLU_rel_pos?"left"==c.cpro_slideLU_abs_pos||"right"==c.cpro_slideLU_abs_pos?(c.ver=c.cpro_slideLU_rel_pos||c.slideLU_rel_pos,c.cpro_slideLU_rel_pos=c.cpro_slideLU_rel_pos||c.slideLU_rel_pos,c.bpos="middle"):(c.ver="0",c.cpro_slideLU_rel_pos=c.cpro_slideLU_rel_pos||c.slideLU_rel_pos,c.bpos=c.cpro_slideLU_rel_pos):(void 0!=c.ver?"left"==c.cpro_slideLU_abs_pos||
"right"==c.cpro_slideLU_abs_pos?c.cpro_slideLU_rel_pos=c.ver:(c.ver="0",c.cpro_slideLU_rel_pos="middle"):void 0!=c.bpos?"left"==c.cpro_slideLU_abs_pos||"right"==c.cpro_slideLU_abs_pos?c.cpro_slideLU_rel_pos="50":(c.ver="0",c.cpro_slideLU_rel_pos="middle"):"left"==c.cpro_slideLU_abs_pos||"right"==c.cpro_slideLU_abs_pos?(c.ver="50",c.cpro_slideLU_rel_pos="50"):(c.ver="0",c.cpro_slideLU_rel_pos="middle"),c.bpos="middle");void 0!=c.cpro_slideLU_out_per||void 0!=c.slideLU_out_per?(c.per=c.cpro_slideLU_out_per||
c.slideLU_out_per,c.cpro_slideLU_out_per=c.cpro_slideLU_out_per||c.slideLU_out_per):void 0!=c.per?c.cpro_slideLU_out_per=c.per||c.slideLU_out_per:(c.cpro_slideLU_out_per="0.3",c.per="0.3");void 0!=c.cpro_slideLU_in_per||void 0!=c.slideLU_in_per?(c.per2=c.cpro_slideLU_in_per||c.slideLU_in_per,c.cpro_slideLU_in_per=c.cpro_slideLU_in_per||c.slideLU_in_per):void 0!=c.per2?c.cpro_slideLU_in_per=c.per2:(c.cpro_slideLU_in_per="1.0",c.per2="1.0");c.curl=g.serviceUrl+g.paramString;k[f]=new d;k[f].init(c);
"u0"===f.split("_")[0]&&(k[f].setUrl(),k[f].slideout());!m&&"u0"!=f.split("_")[0]&&(j.bind(window,"scroll",p),m=!0)}}});})();
